-- RUN THIS IN SUPABASE SQL EDITOR --

-- 1. Create a public 'profiles' table to track users
-- (Supabase Auth users are private, so we need a public table to list them in Admin panel)
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  created_at timestamptz default now()
);

-- 2. Trigger to automatically create profile on Signup
-- This ensures every new user gets a row in 'profiles'
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. Enable RLS on Profiles
alter table profiles enable row level security;

-- 4. Helper function to check if current user is Admin
create or replace function is_admin()
returns boolean as $$
  select auth.email() = 'ishoracharya977@gmail.com';
$$ language sql security definer;

-- 5. UPDATE POLICIES FOR ADMIN ACCESS

-- Profiles Policies
create policy "Public profiles are viewable by everyone" 
  on profiles for select 
  using ( true ); -- Or restrict to just admin + self if you want stricter privacy

create policy "Users can insert their own profile" 
  on profiles for insert 
  with check ( auth.uid() = id );
  
create policy "Admin can delete profiles" 
  on profiles for delete 
  using ( is_admin() );

-- Update Transactions Policies (Allow Admin to View/Delete All)
drop policy if exists "Users can view their own transactions" on transactions;
create policy "Users and Admin can view transactions"
  on transactions for select
  using ( auth.uid() = user_id OR is_admin() );

drop policy if exists "Users can delete their own transactions" on transactions;
create policy "Users and Admin can delete transactions"
  on transactions for delete
  using ( auth.uid() = user_id OR is_admin() );

-- Update Categories Policies
drop policy if exists "Users can view their own categories" on categories;
create policy "Users and Admin can view categories"
  on categories for select
  using ( auth.uid() = user_id OR is_admin() );

drop policy if exists "Users can delete their own categories" on categories;
create policy "Users and Admin can delete categories"
  on categories for delete
  using ( auth.uid() = user_id OR is_admin() );

-- 6. Sales Inquiries Table
CREATE TABLE IF NOT EXISTS sales_inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  company TEXT,
  plan TEXT,
  message TEXT
);

ALTER TABLE sales_inquiries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for everyone" on sales_inquiries for insert with check (true);
CREATE POLICY "Enable select for admin" on sales_inquiries for select using (is_admin());

-- 7. Insert existing users into profiles (if any exist before this script runs)
insert into public.profiles (id, email)
select id, email from auth.users
on conflict (id) do nothing;
